"""
PLOS — Full ISO 3166-1 country list with currency + flag.
Auto-generated. Used by CountrySelector on both backend and frontend.
The 8 countries in COUNTRY_MAP (country_context.py) have hand-curated
localisation info; every other country uses a smart generic template.
"""
from __future__ import annotations
from typing import Dict, List

# ISO code → (name, flag, currency, currency_symbol)
ISO_COUNTRIES: Dict[str, Dict[str, str]] = {
    "AF": {"name": "Afghanistan", "flag": "🇦🇫", "currency": "AFN", "symbol": "؋"},
    "AL": {"name": "Albania", "flag": "🇦🇱", "currency": "ALL", "symbol": "L"},
    "DZ": {"name": "Algeria", "flag": "🇩🇿", "currency": "DZD", "symbol": "DA"},
    "AD": {"name": "Andorra", "flag": "🇦🇩", "currency": "EUR", "symbol": "€"},
    "AO": {"name": "Angola", "flag": "🇦🇴", "currency": "AOA", "symbol": "Kz"},
    "AG": {"name": "Antigua and Barbuda", "flag": "🇦🇬", "currency": "XCD", "symbol": "EC$"},
    "AR": {"name": "Argentina", "flag": "🇦🇷", "currency": "ARS", "symbol": "$"},
    "AM": {"name": "Armenia", "flag": "🇦🇲", "currency": "AMD", "symbol": "֏"},
    "AU": {"name": "Australia", "flag": "🇦🇺", "currency": "AUD", "symbol": "A$"},
    "AT": {"name": "Austria", "flag": "🇦🇹", "currency": "EUR", "symbol": "€"},
    "AZ": {"name": "Azerbaijan", "flag": "🇦🇿", "currency": "AZN", "symbol": "₼"},
    "BS": {"name": "Bahamas", "flag": "🇧🇸", "currency": "BSD", "symbol": "B$"},
    "BH": {"name": "Bahrain", "flag": "🇧🇭", "currency": "BHD", "symbol": ".د.ب"},
    "BD": {"name": "Bangladesh", "flag": "🇧🇩", "currency": "BDT", "symbol": "৳"},
    "BB": {"name": "Barbados", "flag": "🇧🇧", "currency": "BBD", "symbol": "Bds$"},
    "BY": {"name": "Belarus", "flag": "🇧🇾", "currency": "BYN", "symbol": "Br"},
    "BE": {"name": "Belgium", "flag": "🇧🇪", "currency": "EUR", "symbol": "€"},
    "BZ": {"name": "Belize", "flag": "🇧🇿", "currency": "BZD", "symbol": "BZ$"},
    "BJ": {"name": "Benin", "flag": "🇧🇯", "currency": "XOF", "symbol": "CFA"},
    "BT": {"name": "Bhutan", "flag": "🇧🇹", "currency": "BTN", "symbol": "Nu."},
    "BO": {"name": "Bolivia", "flag": "🇧🇴", "currency": "BOB", "symbol": "Bs."},
    "BA": {"name": "Bosnia and Herzegovina", "flag": "🇧🇦", "currency": "BAM", "symbol": "KM"},
    "BW": {"name": "Botswana", "flag": "🇧🇼", "currency": "BWP", "symbol": "P"},
    "BR": {"name": "Brazil", "flag": "🇧🇷", "currency": "BRL", "symbol": "R$"},
    "BN": {"name": "Brunei", "flag": "🇧🇳", "currency": "BND", "symbol": "B$"},
    "BG": {"name": "Bulgaria", "flag": "🇧🇬", "currency": "BGN", "symbol": "лв"},
    "BF": {"name": "Burkina Faso", "flag": "🇧🇫", "currency": "XOF", "symbol": "CFA"},
    "BI": {"name": "Burundi", "flag": "🇧🇮", "currency": "BIF", "symbol": "FBu"},
    "KH": {"name": "Cambodia", "flag": "🇰🇭", "currency": "KHR", "symbol": "៛"},
    "CM": {"name": "Cameroon", "flag": "🇨🇲", "currency": "XAF", "symbol": "FCFA"},
    "CA": {"name": "Canada", "flag": "🇨🇦", "currency": "CAD", "symbol": "C$"},
    "CV": {"name": "Cape Verde", "flag": "🇨🇻", "currency": "CVE", "symbol": "Esc"},
    "CF": {"name": "Central African Republic", "flag": "🇨🇫", "currency": "XAF", "symbol": "FCFA"},
    "TD": {"name": "Chad", "flag": "🇹🇩", "currency": "XAF", "symbol": "FCFA"},
    "CL": {"name": "Chile", "flag": "🇨🇱", "currency": "CLP", "symbol": "CLP$"},
    "CN": {"name": "China", "flag": "🇨🇳", "currency": "CNY", "symbol": "¥"},
    "CO": {"name": "Colombia", "flag": "🇨🇴", "currency": "COP", "symbol": "COL$"},
    "KM": {"name": "Comoros", "flag": "🇰🇲", "currency": "KMF", "symbol": "CF"},
    "CG": {"name": "Congo", "flag": "🇨🇬", "currency": "XAF", "symbol": "FCFA"},
    "CD": {"name": "Congo (DRC)", "flag": "🇨🇩", "currency": "CDF", "symbol": "FC"},
    "CR": {"name": "Costa Rica", "flag": "🇨🇷", "currency": "CRC", "symbol": "₡"},
    "CI": {"name": "Côte d'Ivoire", "flag": "🇨🇮", "currency": "XOF", "symbol": "CFA"},
    "HR": {"name": "Croatia", "flag": "🇭🇷", "currency": "EUR", "symbol": "€"},
    "CU": {"name": "Cuba", "flag": "🇨🇺", "currency": "CUP", "symbol": "₱"},
    "CY": {"name": "Cyprus", "flag": "🇨🇾", "currency": "EUR", "symbol": "€"},
    "CZ": {"name": "Czech Republic", "flag": "🇨🇿", "currency": "CZK", "symbol": "Kč"},
    "DK": {"name": "Denmark", "flag": "🇩🇰", "currency": "DKK", "symbol": "kr"},
    "DJ": {"name": "Djibouti", "flag": "🇩🇯", "currency": "DJF", "symbol": "Fdj"},
    "DM": {"name": "Dominica", "flag": "🇩🇲", "currency": "XCD", "symbol": "EC$"},
    "DO": {"name": "Dominican Republic", "flag": "🇩🇴", "currency": "DOP", "symbol": "RD$"},
    "EC": {"name": "Ecuador", "flag": "🇪🇨", "currency": "USD", "symbol": "$"},
    "EG": {"name": "Egypt", "flag": "🇪🇬", "currency": "EGP", "symbol": "E£"},
    "SV": {"name": "El Salvador", "flag": "🇸🇻", "currency": "USD", "symbol": "$"},
    "GQ": {"name": "Equatorial Guinea", "flag": "🇬🇶", "currency": "XAF", "symbol": "FCFA"},
    "ER": {"name": "Eritrea", "flag": "🇪🇷", "currency": "ERN", "symbol": "Nfk"},
    "EE": {"name": "Estonia", "flag": "🇪🇪", "currency": "EUR", "symbol": "€"},
    "SZ": {"name": "Eswatini", "flag": "🇸🇿", "currency": "SZL", "symbol": "E"},
    "ET": {"name": "Ethiopia", "flag": "🇪🇹", "currency": "ETB", "symbol": "Br"},
    "FJ": {"name": "Fiji", "flag": "🇫🇯", "currency": "FJD", "symbol": "FJ$"},
    "FI": {"name": "Finland", "flag": "🇫🇮", "currency": "EUR", "symbol": "€"},
    "FR": {"name": "France", "flag": "🇫🇷", "currency": "EUR", "symbol": "€"},
    "GA": {"name": "Gabon", "flag": "🇬🇦", "currency": "XAF", "symbol": "FCFA"},
    "GM": {"name": "Gambia", "flag": "🇬🇲", "currency": "GMD", "symbol": "D"},
    "GE": {"name": "Georgia", "flag": "🇬🇪", "currency": "GEL", "symbol": "₾"},
    "DE": {"name": "Germany", "flag": "🇩🇪", "currency": "EUR", "symbol": "€"},
    "GH": {"name": "Ghana", "flag": "🇬🇭", "currency": "GHS", "symbol": "GH₵"},
    "GR": {"name": "Greece", "flag": "🇬🇷", "currency": "EUR", "symbol": "€"},
    "GD": {"name": "Grenada", "flag": "🇬🇩", "currency": "XCD", "symbol": "EC$"},
    "GT": {"name": "Guatemala", "flag": "🇬🇹", "currency": "GTQ", "symbol": "Q"},
    "GN": {"name": "Guinea", "flag": "🇬🇳", "currency": "GNF", "symbol": "FG"},
    "GW": {"name": "Guinea-Bissau", "flag": "🇬🇼", "currency": "XOF", "symbol": "CFA"},
    "GY": {"name": "Guyana", "flag": "🇬🇾", "currency": "GYD", "symbol": "GY$"},
    "HT": {"name": "Haiti", "flag": "🇭🇹", "currency": "HTG", "symbol": "G"},
    "HN": {"name": "Honduras", "flag": "🇭🇳", "currency": "HNL", "symbol": "L"},
    "HK": {"name": "Hong Kong", "flag": "🇭🇰", "currency": "HKD", "symbol": "HK$"},
    "HU": {"name": "Hungary", "flag": "🇭🇺", "currency": "HUF", "symbol": "Ft"},
    "IS": {"name": "Iceland", "flag": "🇮🇸", "currency": "ISK", "symbol": "kr"},
    "IN": {"name": "India", "flag": "🇮🇳", "currency": "INR", "symbol": "₹"},
    "ID": {"name": "Indonesia", "flag": "🇮🇩", "currency": "IDR", "symbol": "Rp"},
    "IR": {"name": "Iran", "flag": "🇮🇷", "currency": "IRR", "symbol": "﷼"},
    "IQ": {"name": "Iraq", "flag": "🇮🇶", "currency": "IQD", "symbol": "ع.د"},
    "IE": {"name": "Ireland", "flag": "🇮🇪", "currency": "EUR", "symbol": "€"},
    "IL": {"name": "Israel", "flag": "🇮🇱", "currency": "ILS", "symbol": "₪"},
    "IT": {"name": "Italy", "flag": "🇮🇹", "currency": "EUR", "symbol": "€"},
    "JM": {"name": "Jamaica", "flag": "🇯🇲", "currency": "JMD", "symbol": "J$"},
    "JP": {"name": "Japan", "flag": "🇯🇵", "currency": "JPY", "symbol": "¥"},
    "JO": {"name": "Jordan", "flag": "🇯🇴", "currency": "JOD", "symbol": "JD"},
    "KZ": {"name": "Kazakhstan", "flag": "🇰🇿", "currency": "KZT", "symbol": "₸"},
    "KE": {"name": "Kenya", "flag": "🇰🇪", "currency": "KES", "symbol": "KSh"},
    "KI": {"name": "Kiribati", "flag": "🇰🇮", "currency": "AUD", "symbol": "A$"},
    "KW": {"name": "Kuwait", "flag": "🇰🇼", "currency": "KWD", "symbol": "KD"},
    "KG": {"name": "Kyrgyzstan", "flag": "🇰🇬", "currency": "KGS", "symbol": "с"},
    "LA": {"name": "Laos", "flag": "🇱🇦", "currency": "LAK", "symbol": "₭"},
    "LV": {"name": "Latvia", "flag": "🇱🇻", "currency": "EUR", "symbol": "€"},
    "LB": {"name": "Lebanon", "flag": "🇱🇧", "currency": "LBP", "symbol": "ل.ل"},
    "LS": {"name": "Lesotho", "flag": "🇱🇸", "currency": "LSL", "symbol": "L"},
    "LR": {"name": "Liberia", "flag": "🇱🇷", "currency": "LRD", "symbol": "L$"},
    "LY": {"name": "Libya", "flag": "🇱🇾", "currency": "LYD", "symbol": "LD"},
    "LI": {"name": "Liechtenstein", "flag": "🇱🇮", "currency": "CHF", "symbol": "CHF"},
    "LT": {"name": "Lithuania", "flag": "🇱🇹", "currency": "EUR", "symbol": "€"},
    "LU": {"name": "Luxembourg", "flag": "🇱🇺", "currency": "EUR", "symbol": "€"},
    "MO": {"name": "Macao", "flag": "🇲🇴", "currency": "MOP", "symbol": "MOP$"},
    "MG": {"name": "Madagascar", "flag": "🇲🇬", "currency": "MGA", "symbol": "Ar"},
    "MW": {"name": "Malawi", "flag": "🇲🇼", "currency": "MWK", "symbol": "MK"},
    "MY": {"name": "Malaysia", "flag": "🇲🇾", "currency": "MYR", "symbol": "RM"},
    "MV": {"name": "Maldives", "flag": "🇲🇻", "currency": "MVR", "symbol": "Rf"},
    "ML": {"name": "Mali", "flag": "🇲🇱", "currency": "XOF", "symbol": "CFA"},
    "MT": {"name": "Malta", "flag": "🇲🇹", "currency": "EUR", "symbol": "€"},
    "MH": {"name": "Marshall Islands", "flag": "🇲🇭", "currency": "USD", "symbol": "$"},
    "MR": {"name": "Mauritania", "flag": "🇲🇷", "currency": "MRU", "symbol": "UM"},
    "MU": {"name": "Mauritius", "flag": "🇲🇺", "currency": "MUR", "symbol": "Rs"},
    "MX": {"name": "Mexico", "flag": "🇲🇽", "currency": "MXN", "symbol": "Mex$"},
    "FM": {"name": "Micronesia", "flag": "🇫🇲", "currency": "USD", "symbol": "$"},
    "MD": {"name": "Moldova", "flag": "🇲🇩", "currency": "MDL", "symbol": "L"},
    "MC": {"name": "Monaco", "flag": "🇲🇨", "currency": "EUR", "symbol": "€"},
    "MN": {"name": "Mongolia", "flag": "🇲🇳", "currency": "MNT", "symbol": "₮"},
    "ME": {"name": "Montenegro", "flag": "🇲🇪", "currency": "EUR", "symbol": "€"},
    "MA": {"name": "Morocco", "flag": "🇲🇦", "currency": "MAD", "symbol": "د.م."},
    "MZ": {"name": "Mozambique", "flag": "🇲🇿", "currency": "MZN", "symbol": "MT"},
    "MM": {"name": "Myanmar", "flag": "🇲🇲", "currency": "MMK", "symbol": "K"},
    "NA": {"name": "Namibia", "flag": "🇳🇦", "currency": "NAD", "symbol": "N$"},
    "NR": {"name": "Nauru", "flag": "🇳🇷", "currency": "AUD", "symbol": "A$"},
    "NP": {"name": "Nepal", "flag": "🇳🇵", "currency": "NPR", "symbol": "रू"},
    "NL": {"name": "Netherlands", "flag": "🇳🇱", "currency": "EUR", "symbol": "€"},
    "NZ": {"name": "New Zealand", "flag": "🇳🇿", "currency": "NZD", "symbol": "NZ$"},
    "NI": {"name": "Nicaragua", "flag": "🇳🇮", "currency": "NIO", "symbol": "C$"},
    "NE": {"name": "Niger", "flag": "🇳🇪", "currency": "XOF", "symbol": "CFA"},
    "NG": {"name": "Nigeria", "flag": "🇳🇬", "currency": "NGN", "symbol": "₦"},
    "KP": {"name": "North Korea", "flag": "🇰🇵", "currency": "KPW", "symbol": "₩"},
    "MK": {"name": "North Macedonia", "flag": "🇲🇰", "currency": "MKD", "symbol": "ден"},
    "NO": {"name": "Norway", "flag": "🇳🇴", "currency": "NOK", "symbol": "kr"},
    "OM": {"name": "Oman", "flag": "🇴🇲", "currency": "OMR", "symbol": "ر.ع."},
    "PK": {"name": "Pakistan", "flag": "🇵🇰", "currency": "PKR", "symbol": "Rs"},
    "PW": {"name": "Palau", "flag": "🇵🇼", "currency": "USD", "symbol": "$"},
    "PS": {"name": "Palestine", "flag": "🇵🇸", "currency": "ILS", "symbol": "₪"},
    "PA": {"name": "Panama", "flag": "🇵🇦", "currency": "PAB", "symbol": "B/."},
    "PG": {"name": "Papua New Guinea", "flag": "🇵🇬", "currency": "PGK", "symbol": "K"},
    "PY": {"name": "Paraguay", "flag": "🇵🇾", "currency": "PYG", "symbol": "₲"},
    "PE": {"name": "Peru", "flag": "🇵🇪", "currency": "PEN", "symbol": "S/"},
    "PH": {"name": "Philippines", "flag": "🇵🇭", "currency": "PHP", "symbol": "₱"},
    "PL": {"name": "Poland", "flag": "🇵🇱", "currency": "PLN", "symbol": "zł"},
    "PT": {"name": "Portugal", "flag": "🇵🇹", "currency": "EUR", "symbol": "€"},
    "QA": {"name": "Qatar", "flag": "🇶🇦", "currency": "QAR", "symbol": "ر.ق"},
    "RO": {"name": "Romania", "flag": "🇷🇴", "currency": "RON", "symbol": "lei"},
    "RU": {"name": "Russia", "flag": "🇷🇺", "currency": "RUB", "symbol": "₽"},
    "RW": {"name": "Rwanda", "flag": "🇷🇼", "currency": "RWF", "symbol": "FRw"},
    "KN": {"name": "Saint Kitts and Nevis", "flag": "🇰🇳", "currency": "XCD", "symbol": "EC$"},
    "LC": {"name": "Saint Lucia", "flag": "🇱🇨", "currency": "XCD", "symbol": "EC$"},
    "VC": {"name": "Saint Vincent", "flag": "🇻🇨", "currency": "XCD", "symbol": "EC$"},
    "WS": {"name": "Samoa", "flag": "🇼🇸", "currency": "WST", "symbol": "T"},
    "SM": {"name": "San Marino", "flag": "🇸🇲", "currency": "EUR", "symbol": "€"},
    "ST": {"name": "São Tomé and Príncipe", "flag": "🇸🇹", "currency": "STN", "symbol": "Db"},
    "SA": {"name": "Saudi Arabia", "flag": "🇸🇦", "currency": "SAR", "symbol": "ر.س"},
    "SN": {"name": "Senegal", "flag": "🇸🇳", "currency": "XOF", "symbol": "CFA"},
    "RS": {"name": "Serbia", "flag": "🇷🇸", "currency": "RSD", "symbol": "дин"},
    "SC": {"name": "Seychelles", "flag": "🇸🇨", "currency": "SCR", "symbol": "SR"},
    "SL": {"name": "Sierra Leone", "flag": "🇸🇱", "currency": "SLL", "symbol": "Le"},
    "SG": {"name": "Singapore", "flag": "🇸🇬", "currency": "SGD", "symbol": "S$"},
    "SK": {"name": "Slovakia", "flag": "🇸🇰", "currency": "EUR", "symbol": "€"},
    "SI": {"name": "Slovenia", "flag": "🇸🇮", "currency": "EUR", "symbol": "€"},
    "SB": {"name": "Solomon Islands", "flag": "🇸🇧", "currency": "SBD", "symbol": "SI$"},
    "SO": {"name": "Somalia", "flag": "🇸🇴", "currency": "SOS", "symbol": "Sh"},
    "ZA": {"name": "South Africa", "flag": "🇿🇦", "currency": "ZAR", "symbol": "R"},
    "KR": {"name": "South Korea", "flag": "🇰🇷", "currency": "KRW", "symbol": "₩"},
    "SS": {"name": "South Sudan", "flag": "🇸🇸", "currency": "SSP", "symbol": "SSP"},
    "ES": {"name": "Spain", "flag": "🇪🇸", "currency": "EUR", "symbol": "€"},
    "LK": {"name": "Sri Lanka", "flag": "🇱🇰", "currency": "LKR", "symbol": "Rs"},
    "SD": {"name": "Sudan", "flag": "🇸🇩", "currency": "SDG", "symbol": "ج.س."},
    "SR": {"name": "Suriname", "flag": "🇸🇷", "currency": "SRD", "symbol": "$"},
    "SE": {"name": "Sweden", "flag": "🇸🇪", "currency": "SEK", "symbol": "kr"},
    "CH": {"name": "Switzerland", "flag": "🇨🇭", "currency": "CHF", "symbol": "CHF"},
    "SY": {"name": "Syria", "flag": "🇸🇾", "currency": "SYP", "symbol": "£"},
    "TW": {"name": "Taiwan", "flag": "🇹🇼", "currency": "TWD", "symbol": "NT$"},
    "TJ": {"name": "Tajikistan", "flag": "🇹🇯", "currency": "TJS", "symbol": "SM"},
    "TZ": {"name": "Tanzania", "flag": "🇹🇿", "currency": "TZS", "symbol": "TSh"},
    "TH": {"name": "Thailand", "flag": "🇹🇭", "currency": "THB", "symbol": "฿"},
    "TL": {"name": "Timor-Leste", "flag": "🇹🇱", "currency": "USD", "symbol": "$"},
    "TG": {"name": "Togo", "flag": "🇹🇬", "currency": "XOF", "symbol": "CFA"},
    "TO": {"name": "Tonga", "flag": "🇹🇴", "currency": "TOP", "symbol": "T$"},
    "TT": {"name": "Trinidad and Tobago", "flag": "🇹🇹", "currency": "TTD", "symbol": "TT$"},
    "TN": {"name": "Tunisia", "flag": "🇹🇳", "currency": "TND", "symbol": "د.ت"},
    "TR": {"name": "Turkey", "flag": "🇹🇷", "currency": "TRY", "symbol": "₺"},
    "TM": {"name": "Turkmenistan", "flag": "🇹🇲", "currency": "TMT", "symbol": "T"},
    "TV": {"name": "Tuvalu", "flag": "🇹🇻", "currency": "AUD", "symbol": "A$"},
    "UG": {"name": "Uganda", "flag": "🇺🇬", "currency": "UGX", "symbol": "USh"},
    "UA": {"name": "Ukraine", "flag": "🇺🇦", "currency": "UAH", "symbol": "₴"},
    "AE": {"name": "United Arab Emirates", "flag": "🇦🇪", "currency": "AED", "symbol": "د.إ"},
    "GB": {"name": "United Kingdom", "flag": "🇬🇧", "currency": "GBP", "symbol": "£"},
    "US": {"name": "United States", "flag": "🇺🇸", "currency": "USD", "symbol": "$"},
    "UY": {"name": "Uruguay", "flag": "🇺🇾", "currency": "UYU", "symbol": "$U"},
    "UZ": {"name": "Uzbekistan", "flag": "🇺🇿", "currency": "UZS", "symbol": "лв"},
    "VU": {"name": "Vanuatu", "flag": "🇻🇺", "currency": "VUV", "symbol": "VT"},
    "VA": {"name": "Vatican City", "flag": "🇻🇦", "currency": "EUR", "symbol": "€"},
    "VE": {"name": "Venezuela", "flag": "🇻🇪", "currency": "VES", "symbol": "Bs"},
    "VN": {"name": "Vietnam", "flag": "🇻🇳", "currency": "VND", "symbol": "₫"},
    "YE": {"name": "Yemen", "flag": "🇾🇪", "currency": "YER", "symbol": "﷼"},
    "ZM": {"name": "Zambia", "flag": "🇿🇲", "currency": "ZMW", "symbol": "ZK"},
    "ZW": {"name": "Zimbabwe", "flag": "🇿🇼", "currency": "ZWL", "symbol": "Z$"},
}


def iso_country(code: str) -> Dict[str, str]:
    return ISO_COUNTRIES.get((code or "").upper(), ISO_COUNTRIES["US"])


def all_countries() -> List[Dict[str, str]]:
    return [{"code": k, **v} for k, v in sorted(ISO_COUNTRIES.items(), key=lambda x: x[1]["name"])]
